-- Credits to original theme https://github.com/olivercederborg/poimandres.nvim
-- This is a modified version by @kayuxcodes

local M = {}

M.base_30 = {
  white = "#FFFFFF",
  black = "#1b1e28",
  darker_black = "#232633",
  black2 = "#1b1e28",
  one_bg = "#303340",
  one_bg2 = "#494b53",
  one_bg3 = "#5f6269",
  grey = "#506477",
  grey_fg = "#767C9D",
  grey_fg2 = "#506477",
  light_grey = "#91B4D5",
  red = "#F45050",
  baby_pink = "#FCC5E9",
  pink = "#FAE4FC",
  line = "#303340",
  green = "#5FB3A1",
  vibrant_green = "#5FB3A1",
  nord_blue = "#64CCC5",
  blue = "#89DDFF",
  seablue = "#ADD7FF",
  yellow = "#FFFAC2",
  sun = "#FFA33C",
  purple = "#a6accd",
  dark_purple = "#E4F0FB",
  teal = "#5DE4C7",
  orange = "#91B4D5",
  cyan = "#89DDFF",
  statusline_bg = "#1b1e28",
  lightbg = "#a6accd",
  pmenu_bg = "#303340",
  folder_bg = "#91B4D5",
}

M.base_16 = {
  base00 = "#1b1e28",
  base01 = "#a6accd",
  base02 = "#303340",
  base03 = "#a6accd",
  base04 = "#171922",
  base05 = "#a6accd",
  base06 = "#a6accd",
  base07 = "#a6accd",
  base08 = "#e4f0fb",
  base09 = "#D80032",
  base0A = "#ADD7FF",
  base0B = "#5DE4C7",
  base0C = "#5DE4C7",
  base0D = "#5DE4C7",
  base0E = "#a6accd",
  base0F = "#FFFFFF",
}
M.polish_hl = {
  ["@variable"] = { fg = "#E4F0FB" },
  ["@boolean"] = { link = "Boolean" },
  Comment = { fg = "#767C9D" },
  ["@variable.builtin"] = { fg = "#E4F0FB" },
  ["@constant.builtin"] = { fg = "#ADD7FF" },
  ["@constant.falsy"] = { fg = "#D80032" },
  ["@constructor"] = { fg = "#767C9D" },
  ["@function.builtin"] = { fg = "#ADD7FF" },
  ["@function"] = { fg = "#ADD7FF" },
  ["@function.call"] = { fg = "#A6ACCD" },
  ["@keyword"] = { fg = "#91B4D5" },
  ["@keyword.return"] = { fg = "#5FB3A1" },
  ["@keyword.function"] = { fg = "#91B4D5" },
  ["@keyword.operator"] = { fg = "#ADD7FF" },
  ["@field"] = { fg = "#E4F0FB" },
  ["@label"] = { fg = "#91B4D5" },
  Include = { fg = "#89DDFF" },
  ["@method"] = { fg = "#5DE4C7" },
  ["@operator"] = { link = "Operator" },
  ["@parameter"] = { fg = "#E4F0FB" },
  ["@property"] = { fg = "#ADD7FF" },
  ["@punctuation.delimiter"] = { fg = "#ADD7FF" },
  ["@punctuation.special"] = { fg = "#91B4D5" },
  ["@punctuation.bracket"] = { fg = "#767C9D" },
  ["@string"] = { link = "String" },
  ["@string.escape"] = { fg = "#D0679D" },
  Tag = { fg = "#5DE4C7" },
  ["@tag.attribute"] = { fg = "#A6ACCD", link = "" },
  ["@tag.delimiter"] = { fg = "#E4F0FB" },
  ["@txt"] = { fg = "#E4F0FB" },
  ["@title"] = { fg = "#5DE4C7", style = "bold" },
  Type = { fg = "#767C9D" },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { link = "Type" },
  CmpItemAbbr = { fg = "#767C9D" },
  CmpItemAbbrDeprecated = { fg = "#D0679D" },
  CmpItemAbbrMatch = { fg = "#E4F0FB" },
  CmpItemAbbrMatchFuzzy = { fg = "#5DE4C7" },
  CmpItemKind = { fg = "#91B4D5" },
  CmpItemKindClass = { fg = "#FFFAC2" },
  CmpItemKindFunction = { fg = "#89DDFF" },
  CmpItemKindInterface = { fg = "#ADD7FF" },
  CmpItemKindMethod = { fg = "#D0679D" },
  CmpItemKindSnippet = { fg = "#A6ACCD" },
  CmpItemKindVariable = { fg = "#5DE4C7" },
  ["CmpSel"] = { fg = "#E4F0FB", link = "" },
  St_CommandmodeText = { fg = "#5DE4C7" },
  St_CommandModeSep = { fg = "#5DE4C7" },
  St_CommandMode = { bg = "#5DE4C7" },
  St_TerminalmodeText = { fg = "#FFFAC2" },
  St_TerminalModeSep = { fg = "#FFFAC2" },
  St_TerminalMode = { bg = "#FFFAC2" },
}
M.type = "dark"

M = require("base46").override_theme(M, "poimandres")

return M
